'''''
Need to see why i didnt get a logger info when i ran exception.py'''